[package]

name = "habitrpg"
version = "0.0.5"
authors = ["Jonas Hietala <mail@jonashietala.se>"]

[dependencies.time]

git = "https://github.com/rust-lang/time"

[dependencies]
regex = "0.1.8"
regex_macros = "0.1.8"
hyper = "0.6.6"
url = "0.2.36"
rustc-serialize = "0.3"
