[package]

name = "habitrpg"
version = "0.0.1"
authors = ["Jonas Hietala <mail@jonashietala.se>"]

[dependencies.time]

git = "https://github.com/rust-lang/time"

[dependencies.http]

git = "https://github.com/chris-morgan/rust-http.git"

